const BUCKET_NAME = 'savvyappphotos';
const IAM_USER_KEY = 'AKIAJCPDDFH7TPHH6X6A';
const IAM_USER_SECRET = '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';

module.exports = {
  BUCKET_NAME: BUCKET_NAME,
  IAM_USER_KEY: IAM_USER_KEY,
  IAM_USER_SECRET: IAM_USER_SECRET
}
