const BUCKET_NAME = 'savvyappphotos';
const IAM_USER_KEY = 'AKIAIUNQ2IP6UJK7GATQ';
const IAM_USER_SECRET = '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';

module.exports = {
  BUCKET_NAME: BUCKET_NAME,
  IAM_USER_KEY: IAM_USER_KEY,
  IAM_USER_SECRET: IAM_USER_SECRET
}
